const cars = [
    { name: 'Ford Focus',
      cost: `&#xa3;7,599`,
      image:'./img-item/ford-focus.png',   
    },
    { name: 'Skoda Fabia',
      cost: `&#xa3;6,500`,
      image:'./img-item/skoda-fabia.png',   
    },
    { name: 'Honda Civic',
      cost: `&#xa3;10,400`,
      image:'./img-item/honda-civic.png',   
    },
    { name: 'Vauxhall Corsa',
      cost: `&#xa3;3,999`,
      image:'./img-item/vauxhall-corsa.png',   
    },
    { name: 'Renault Clio',
      cost: `&#xa3;4,999`,
      image:'./img-item/renault-clio.png',   
    },
    { name: 'Volkswagen Polo',
      cost: `&#xa3;1,999`,
      image:'./img-item/volkswagen-polo.png',   
    },
    { name: 'Seat Lbiza',
      cost: `&#xa3;6,850`,
      image:'./img-item/seat-lbiza.png',   
    },
    { name: 'BMW - i5',
      cost: `&#xa3;8,950`,
      image:'./img-item/bmw-i5.png',   
    } 
]; 